# AnsibleGroup represents a group in ansible that may contain multiple hosts or subgroups.

apiVersion: ansible-operator.lightjack.de
kind: AnsibleGroup
metadata:
  name: foo
  namespace: default
spec:
  ansibleName: foo # required
  hosts:
    # List of AnsibleHost refs in the same namespace
    - name: baz
  groups:
    # List of AnsibleGroup refs in the same namespace (subgroups)
    - name: bar
  groupVars: |
    arbitrary string value that will be inserted into the group's vars block
