# AnsibleGroup represents a group in ansible that may contain multiple hosts or subgroups.

apiVersion: ansible-operator.lightjack.de
kind: AnsibleGroup
metadata:
  name: foo
  namespace: default
spec:
  ansibleName: foo # default to metadata.name if not set
  hosts:
    # List of AnsibleHost refs in the same namespace
    - name: baz
  subgroups:
    # List of AnsibleGroup refs in the same namespace
    - name: bar
  groupVars: |
    arbitrary string value that will be inserted into the host's vars block
