---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - ansible-operator.lightjack.de
  resources:
  - ansiblegroups
  - ansiblehosts
  - ansibleplaybooks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ansible-operator.lightjack.de
  resources:
  - ansiblegroups/finalizers
  - ansiblehosts/finalizers
  - ansibleplaybooks/finalizers
  verbs:
  - update
- apiGroups:
  - ansible-operator.lightjack.de
  resources:
  - ansiblegroups/status
  - ansiblehosts/status
  - ansibleplaybooks/status
  verbs:
  - get
  - patch
  - update
