apiVersion: ansible-operator.lightjack.de/v1alpha1
kind: AnsiblePlaybook
metadata:
  labels:
    app.kubernetes.io/name: ansible-operator
    app.kubernetes.io/managed-by: kustomize
  name: ansibleplaybook-sample
spec:
  # TODO(user): Add fields here
