//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnsibleGroup) DeepCopyInto(out *AnsibleGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnsibleGroup.
func (in *AnsibleGroup) DeepCopy() *AnsibleGroup {
	if in == nil {
		return nil
	}
	out := new(AnsibleGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AnsibleGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnsibleGroupList) DeepCopyInto(out *AnsibleGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AnsibleGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnsibleGroupList.
func (in *AnsibleGroupList) DeepCopy() *AnsibleGroupList {
	if in == nil {
		return nil
	}
	out := new(AnsibleGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AnsibleGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnsibleGroupSpec) DeepCopyInto(out *AnsibleGroupSpec) {
	*out = *in
	if in.Hosts != nil {
		in, out := &in.Hosts, &out.Hosts
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnsibleGroupSpec.
func (in *AnsibleGroupSpec) DeepCopy() *AnsibleGroupSpec {
	if in == nil {
		return nil
	}
	out := new(AnsibleGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnsibleGroupStatus) DeepCopyInto(out *AnsibleGroupStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnsibleGroupStatus.
func (in *AnsibleGroupStatus) DeepCopy() *AnsibleGroupStatus {
	if in == nil {
		return nil
	}
	out := new(AnsibleGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnsibleHost) DeepCopyInto(out *AnsibleHost) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnsibleHost.
func (in *AnsibleHost) DeepCopy() *AnsibleHost {
	if in == nil {
		return nil
	}
	out := new(AnsibleHost)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AnsibleHost) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnsibleHostConnection) DeepCopyInto(out *AnsibleHostConnection) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnsibleHostConnection.
func (in *AnsibleHostConnection) DeepCopy() *AnsibleHostConnection {
	if in == nil {
		return nil
	}
	out := new(AnsibleHostConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnsibleHostList) DeepCopyInto(out *AnsibleHostList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AnsibleHost, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnsibleHostList.
func (in *AnsibleHostList) DeepCopy() *AnsibleHostList {
	if in == nil {
		return nil
	}
	out := new(AnsibleHostList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AnsibleHostList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnsibleHostPrivilege) DeepCopyInto(out *AnsibleHostPrivilege) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnsibleHostPrivilege.
func (in *AnsibleHostPrivilege) DeepCopy() *AnsibleHostPrivilege {
	if in == nil {
		return nil
	}
	out := new(AnsibleHostPrivilege)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnsibleHostSSH) DeepCopyInto(out *AnsibleHostSSH) {
	*out = *in
	out.SSHKeySecretRef = in.SSHKeySecretRef
	out.SSHHostKeySecretRef = in.SSHHostKeySecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnsibleHostSSH.
func (in *AnsibleHostSSH) DeepCopy() *AnsibleHostSSH {
	if in == nil {
		return nil
	}
	out := new(AnsibleHostSSH)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnsibleHostSpec) DeepCopyInto(out *AnsibleHostSpec) {
	*out = *in
	out.Connection = in.Connection
	out.SSH = in.SSH
	if in.Privilege != nil {
		in, out := &in.Privilege, &out.Privilege
		*out = new(AnsibleHostPrivilege)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnsibleHostSpec.
func (in *AnsibleHostSpec) DeepCopy() *AnsibleHostSpec {
	if in == nil {
		return nil
	}
	out := new(AnsibleHostSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnsibleHostStatus) DeepCopyInto(out *AnsibleHostStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnsibleHostStatus.
func (in *AnsibleHostStatus) DeepCopy() *AnsibleHostStatus {
	if in == nil {
		return nil
	}
	out := new(AnsibleHostStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnsiblePlaybook) DeepCopyInto(out *AnsiblePlaybook) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnsiblePlaybook.
func (in *AnsiblePlaybook) DeepCopy() *AnsiblePlaybook {
	if in == nil {
		return nil
	}
	out := new(AnsiblePlaybook)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AnsiblePlaybook) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnsiblePlaybookGit) DeepCopyInto(out *AnsiblePlaybookGit) {
	*out = *in
	out.Repo = in.Repo
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnsiblePlaybookGit.
func (in *AnsiblePlaybookGit) DeepCopy() *AnsiblePlaybookGit {
	if in == nil {
		return nil
	}
	out := new(AnsiblePlaybookGit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnsiblePlaybookInline) DeepCopyInto(out *AnsiblePlaybookInline) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnsiblePlaybookInline.
func (in *AnsiblePlaybookInline) DeepCopy() *AnsiblePlaybookInline {
	if in == nil {
		return nil
	}
	out := new(AnsiblePlaybookInline)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnsiblePlaybookList) DeepCopyInto(out *AnsiblePlaybookList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AnsiblePlaybook, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnsiblePlaybookList.
func (in *AnsiblePlaybookList) DeepCopy() *AnsiblePlaybookList {
	if in == nil {
		return nil
	}
	out := new(AnsiblePlaybookList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AnsiblePlaybookList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnsiblePlaybookRepo) DeepCopyInto(out *AnsiblePlaybookRepo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnsiblePlaybookRepo.
func (in *AnsiblePlaybookRepo) DeepCopy() *AnsiblePlaybookRepo {
	if in == nil {
		return nil
	}
	out := new(AnsiblePlaybookRepo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnsiblePlaybookSpec) DeepCopyInto(out *AnsiblePlaybookSpec) {
	*out = *in
	out.Inline = in.Inline
	out.Git = in.Git
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnsiblePlaybookSpec.
func (in *AnsiblePlaybookSpec) DeepCopy() *AnsiblePlaybookSpec {
	if in == nil {
		return nil
	}
	out := new(AnsiblePlaybookSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnsiblePlaybookStatus) DeepCopyInto(out *AnsiblePlaybookStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnsiblePlaybookStatus.
func (in *AnsiblePlaybookStatus) DeepCopy() *AnsiblePlaybookStatus {
	if in == nil {
		return nil
	}
	out := new(AnsiblePlaybookStatus)
	in.DeepCopyInto(out)
	return out
}
