---
apiVersion: v1
kind: Service
metadata:
  name: ssh-node-1
  namespace: default
  labels:
    app: ssh-node
    node: "1"
spec:
  type: ClusterIP
  ports:
    - name: ssh
      port: 22
      targetPort: 22
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: ssh-node-1
  namespace: default
  labels:
    app: ssh-node
    node: "1"
subsets:
  - addresses:
      - ip: 172.30.0.11
    ports:
      - name: ssh
        port: 22
        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: ssh-node-2
  namespace: default
  labels:
    app: ssh-node
    node: "2"
spec:
  type: ClusterIP
  ports:
    - name: ssh
      port: 22
      targetPort: 22
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: ssh-node-2
  namespace: default
  labels:
    app: ssh-node
    node: "2"
subsets:
  - addresses:
      - ip: 172.30.0.12
    ports:
      - name: ssh
        port: 22
        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: ssh-node-3
  namespace: default
  labels:
    app: ssh-node
    node: "3"
spec:
  type: ClusterIP
  ports:
    - name: ssh
      port: 22
      targetPort: 22
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: ssh-node-3
  namespace: default
  labels:
    app: ssh-node
    node: "3"
subsets:
  - addresses:
      - ip: 172.30.0.13
    ports:
      - name: ssh
        port: 22
        protocol: TCP
