name: Test Chart

on:
  pull_request:

permissions:
  contents: read

jobs:
  test-e2e:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v6

      - name: Install Nix
        uses: cachix/install-nix-action@v31.9.0
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Test helm deployment
        run: |
          nix develop --command bash -c "
            set -euxo pipefail
            export KUBECONFIG=$(mktemp)
            kind create cluster
            helm lint ./dist/chart
            make helm-deploy IMG=ansible-operator:v0.1.0
            make helm-status
          "
